"""empty message

Revision ID: e827978e024d
Revises: 
Create Date: 2020-04-09 16:48:11.554100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e827978e024d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_details',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('login_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('u_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('role_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_on', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=700), autoincrement=False, nullable=True),
    sa.Column('personnel_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('external_status', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=u'user_details_pkey'),
    sa.UniqueConstraint('login_id', name=u'user_details_login_id_key'),
    sa.UniqueConstraint('personnel_id', name=u'user_details_personnel_id_key')
    )
    # ### end Alembic commands ###
